"""Pydantic request/response schemas."""

from app.schemas.addresses import AddressRouteContractResponse, AddressSummary
from app.schemas.auth import (
    AccountClosureRequest,
    AccountClosureResponse,
    AuthAccountSummary,
    AuthSecuritySummary,
    AuthSessionResponse,
    AuthSessionSummary,
    ChangePasswordRequest,
    ChangePasswordResponse,
    ForgotPasswordRequest,
    ForgotPasswordResponse,
    LoginRequest,
    LogoutResponse,
    LogoutRequest,
    RevokeOtherSessionsResponse,
    RevokeSessionResponse,
    ResendEmailVerificationResponse,
    ResetPasswordRequest,
    ResetPasswordResponse,
    SessionDeviceListResponse,
    SessionDeviceSummary,
    SignupRequest,
    TwoFactorChallengeResponse,
    TwoFactorCodeChallengeRequest,
    TwoFactorEnrollmentResponse,
    TwoFactorProtectedActionRequest,
    TwoFactorRecoveryCodesResponse,
    TwoFactorVerifyRequest,
    VerifyEmailRequest,
    VerifyEmailResponse,
)
from app.schemas.communication_preferences import (
    CommunicationPreferenceRouteContractResponse,
    CommunicationPreferenceSummary,
)
from app.schemas.common import (
    ApiErrorDetail,
    ApiErrorResponse,
    CursorPageInfo,
    CursorPageResponse,
    MutationSuccessResponse,
)
from app.schemas.profiles import (
    DiscordProfileDisplaySummary,
    ProfileRouteContractResponse,
    ProfileSettingsReadResponse,
    ProfileSettingsSummary,
)

__all__ = [
    "AddressRouteContractResponse",
    "AddressSummary",
    "AuthAccountSummary",
    "AccountClosureRequest",
    "AccountClosureResponse",
    "AuthSecuritySummary",
    "AuthSessionResponse",
    "AuthSessionSummary",
    "ApiErrorDetail",
    "ApiErrorResponse",
    "ChangePasswordRequest",
    "ChangePasswordResponse",
    "CommunicationPreferenceRouteContractResponse",
    "CommunicationPreferenceSummary",
    "CursorPageInfo",
    "CursorPageResponse",
    "DiscordProfileDisplaySummary",
    "ForgotPasswordRequest",
    "ForgotPasswordResponse",
    "LoginRequest",
    "MutationSuccessResponse",
    "LogoutResponse",
    "LogoutRequest",
    "ProfileRouteContractResponse",
    "ProfileSettingsReadResponse",
    "ProfileSettingsSummary",
    "ResendEmailVerificationResponse",
    "RevokeOtherSessionsResponse",
    "RevokeSessionResponse",
    "ResetPasswordRequest",
    "ResetPasswordResponse",
    "SessionDeviceListResponse",
    "SessionDeviceSummary",
    "SignupRequest",
    "TwoFactorChallengeResponse",
    "TwoFactorCodeChallengeRequest",
    "TwoFactorEnrollmentResponse",
    "TwoFactorProtectedActionRequest",
    "TwoFactorRecoveryCodesResponse",
    "TwoFactorVerifyRequest",
    "VerifyEmailRequest",
    "VerifyEmailResponse",
]
